development:
  adapter: sqlite3
  encoding: unicode
  database: uscis_dev
  pool: 5
  username:
  password:

test:
  adapter: sqlite3
  encoding: unicode
  database: uscis_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: uscis_prod
  host: localhost
  pool: 5
  username:
  password:
