Status.find_or_create_by_name!(name: 'Acceptance')
Status.find_or_create_by_name!(name: 'Initial Review')
Status.find_or_create_by_name!(name: 'Request for Evidence')
Status.find_or_create_by_name!(name: 'Request for Evidence Response Review')
Status.find_or_create_by_name!(name: 'Testing and Interview')
Status.find_or_create_by_name!(name: 'Decision')
Status.find_or_create_by_name!(name: 'Post Decision Activity')
Status.find_or_create_by_name!(name: 'Oath Ceremony')
Status.find_or_create_by_name!(name: 'Card/ Document Production')
